# Generated by Django 5.2.6 on 2025-09-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="markup_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank to use global markup.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="notes",
            field=models.TextField(blank=True, help_text="Admin notes.", null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="user_price_per_1000",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Price for users per 1000 units.",
                max_digits=10,
            ),
        ),
    ]
