# Generated by Django 5.2.6 on 2025-09-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_rewarded_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
